-- Insert Ford Fixed Expense Sub-Metric Mappings for FORD6 sheet
-- Parts Department (column Y) - rows 5-25
INSERT INTO financial_cell_mappings (brand, department_name, metric_key, sheet_name, cell_reference, name_cell_reference, parent_metric_key, is_sub_metric)
VALUES
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:00', 'FORD6', 'Y5', 'B5', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:01', 'FORD6', 'Y6', 'B6', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:02', 'FORD6', 'Y7', 'B7', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:03', 'FORD6', 'Y8', 'B8', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:04', 'FORD6', 'Y9', 'B9', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:05', 'FORD6', 'Y10', 'B10', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:06', 'FORD6', 'Y11', 'B11', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:07', 'FORD6', 'Y12', 'B12', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:08', 'FORD6', 'Y13', 'B13', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:09', 'FORD6', 'Y14', 'B14', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:10', 'FORD6', 'Y15', 'B15', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:11', 'FORD6', 'Y16', 'B16', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:12', 'FORD6', 'Y17', 'B17', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:13', 'FORD6', 'Y18', 'B18', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:14', 'FORD6', 'Y19', 'B19', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:15', 'FORD6', 'Y20', 'B20', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:16', 'FORD6', 'Y21', 'B21', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:17', 'FORD6', 'Y22', 'B22', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:18', 'FORD6', 'Y23', 'B23', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:19', 'FORD6', 'Y24', 'B24', 'total_fixed_expense', true),
  ('Ford', 'Parts Department', 'sub:total_fixed_expense:20', 'FORD6', 'Y25', 'B25', 'total_fixed_expense', true),

-- Service Department (column Z) - rows 5-25  
  ('Ford', 'Service Department', 'sub:total_fixed_expense:00', 'FORD6', 'Z5', 'B5', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:01', 'FORD6', 'Z6', 'B6', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:02', 'FORD6', 'Z7', 'B7', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:03', 'FORD6', 'Z8', 'B8', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:04', 'FORD6', 'Z9', 'B9', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:05', 'FORD6', 'Z10', 'B10', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:06', 'FORD6', 'Z11', 'B11', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:07', 'FORD6', 'Z12', 'B12', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:08', 'FORD6', 'Z13', 'B13', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:09', 'FORD6', 'Z14', 'B14', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:10', 'FORD6', 'Z15', 'B15', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:11', 'FORD6', 'Z16', 'B16', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:12', 'FORD6', 'Z17', 'B17', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:13', 'FORD6', 'Z18', 'B18', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:14', 'FORD6', 'Z19', 'B19', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:15', 'FORD6', 'Z20', 'B20', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:16', 'FORD6', 'Z21', 'B21', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:17', 'FORD6', 'Z22', 'B22', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:18', 'FORD6', 'Z23', 'B23', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:19', 'FORD6', 'Z24', 'B24', 'total_fixed_expense', true),
  ('Ford', 'Service Department', 'sub:total_fixed_expense:20', 'FORD6', 'Z25', 'B25', 'total_fixed_expense', true);